### ISSUE TITLE
Rosinha dos botões do menu

### ISSUE THREAD

**Issue by thcborges** [compcederj/compcederj.github.io#30]
Como eu tenho ódio desse rosinha que eu ainda não consegui tirar

**Comment by marcello-telles** [comment]
Foi corrigido? Pq lembro que quando um dos botões era selecionado o outro ficava rosa, e isso não está mais acontecendo.

**Comment by thcborges** [comment]
Eu ainda não mexi nisso, não.

Em 14 de fev de 2018 14:49, "Marcello Telles" <notifications@github.com>
escreveu:

**Comment by marcello-telles** [comment]
Removi o rosa de tom mais forte ao clicar, deixei apenas o salmão do hover: https://marcello-telles.github.io/compcederj.github.io/
